// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/hnsw_index.dart';
import 'api/semantic_chunker.dart';
import 'api/simple.dart';
import 'api/simple_rag.dart';
import 'api/source_rag.dart';
import 'api/tokenizer.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 923808550;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_mobile_rag_engine',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<int> crateApiSourceRagAddChunks({
    required String dbPath,
    required PlatformInt64 sourceId,
    required List<ChunkData> chunks,
  });

  Future<AddDocumentResult> crateApiSimpleRagAddDocument({
    required String dbPath,
    required String content,
    required List<double> embedding,
  });

  Future<void> crateApiSimpleRagAddDocumentSimple({
    required String dbPath,
    required String content,
    required List<double> embedding,
  });

  Future<AddSourceResult> crateApiSourceRagAddSource({
    required String dbPath,
    required String content,
    String? metadata,
  });

  Future<void> crateApiHnswIndexBuildHnswIndex({
    required List<(PlatformInt64, Float32List)> points,
  });

  double crateApiSimpleRagCalculateCosineSimilarity({
    required List<double> vecA,
    required List<double> vecB,
  });

  Future<void> crateApiSimpleRagClearAllDocuments({required String dbPath});

  Future<void> crateApiHnswIndexClearHnswIndex();

  String crateApiTokenizerDecodeTokens({required List<int> tokenIds});

  Future<void> crateApiSourceRagDeleteSource({
    required String dbPath,
    required PlatformInt64 sourceId,
  });

  Future<EmbeddingPoint> crateApiHnswIndexEmbeddingPointNew({
    required PlatformInt64 id,
    required List<double> embedding,
  });

  Future<PlatformInt64> crateApiSimpleRagGetDocumentCount({
    required String dbPath,
  });

  Future<String?> crateApiSourceRagGetSource({
    required String dbPath,
    required PlatformInt64 sourceId,
  });

  Future<List<String>> crateApiSourceRagGetSourceChunks({
    required String dbPath,
    required PlatformInt64 sourceId,
  });

  Future<SourceStats> crateApiSourceRagGetSourceStats({required String dbPath});

  int crateApiTokenizerGetVocabSize();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiSimpleRagInitDb({required String dbPath});

  Future<void> crateApiSourceRagInitSourceDb({required String dbPath});

  Future<void> crateApiTokenizerInitTokenizer({required String tokenizerPath});

  Future<bool> crateApiHnswIndexIsHnswIndexLoaded();

  Future<void> crateApiSourceRagRebuildChunkHnswIndex({required String dbPath});

  Future<void> crateApiSimpleRagRebuildHnswIndex({required String dbPath});

  Future<List<ChunkSearchResult>> crateApiSourceRagSearchChunks({
    required String dbPath,
    required List<double> queryEmbedding,
    required int topK,
  });

  Future<List<HnswSearchResult>> crateApiHnswIndexSearchHnsw({
    required List<double> queryEmbedding,
    required BigInt topK,
  });

  Future<List<String>> crateApiSimpleRagSearchSimilar({
    required String dbPath,
    required List<double> queryEmbedding,
    required int topK,
  });

  List<SemanticChunk> crateApiSemanticChunkerSemanticChunk({
    required String text,
    required int maxChars,
  });

  List<SemanticChunk> crateApiSemanticChunkerSemanticChunkWithOverlap({
    required String text,
    required int maxChars,
    required int overlapChars,
  });

  Uint32List crateApiTokenizerTokenize({required String text});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<int> crateApiSourceRagAddChunks({
    required String dbPath,
    required PlatformInt64 sourceId,
    required List<ChunkData> chunks,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_i_64(sourceId, serializer);
          sse_encode_list_chunk_data(chunks, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSourceRagAddChunksConstMeta,
        argValues: [dbPath, sourceId, chunks],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSourceRagAddChunksConstMeta => const TaskConstMeta(
    debugName: "add_chunks",
    argNames: ["dbPath", "sourceId", "chunks"],
  );

  @override
  Future<AddDocumentResult> crateApiSimpleRagAddDocument({
    required String dbPath,
    required String content,
    required List<double> embedding,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_String(content, serializer);
          sse_encode_list_prim_f_32_loose(embedding, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_add_document_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleRagAddDocumentConstMeta,
        argValues: [dbPath, content, embedding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRagAddDocumentConstMeta =>
      const TaskConstMeta(
        debugName: "add_document",
        argNames: ["dbPath", "content", "embedding"],
      );

  @override
  Future<void> crateApiSimpleRagAddDocumentSimple({
    required String dbPath,
    required String content,
    required List<double> embedding,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_String(content, serializer);
          sse_encode_list_prim_f_32_loose(embedding, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleRagAddDocumentSimpleConstMeta,
        argValues: [dbPath, content, embedding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRagAddDocumentSimpleConstMeta =>
      const TaskConstMeta(
        debugName: "add_document_simple",
        argNames: ["dbPath", "content", "embedding"],
      );

  @override
  Future<AddSourceResult> crateApiSourceRagAddSource({
    required String dbPath,
    required String content,
    String? metadata,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_String(content, serializer);
          sse_encode_opt_String(metadata, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_add_source_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSourceRagAddSourceConstMeta,
        argValues: [dbPath, content, metadata],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSourceRagAddSourceConstMeta => const TaskConstMeta(
    debugName: "add_source",
    argNames: ["dbPath", "content", "metadata"],
  );

  @override
  Future<void> crateApiHnswIndexBuildHnswIndex({
    required List<(PlatformInt64, Float32List)> points,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_record_i_64_list_prim_f_32_strict(points, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHnswIndexBuildHnswIndexConstMeta,
        argValues: [points],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHnswIndexBuildHnswIndexConstMeta =>
      const TaskConstMeta(debugName: "build_hnsw_index", argNames: ["points"]);

  @override
  double crateApiSimpleRagCalculateCosineSimilarity({
    required List<double> vecA,
    required List<double> vecB,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_32_loose(vecA, serializer);
          sse_encode_list_prim_f_32_loose(vecB, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleRagCalculateCosineSimilarityConstMeta,
        argValues: [vecA, vecB],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRagCalculateCosineSimilarityConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_cosine_similarity",
        argNames: ["vecA", "vecB"],
      );

  @override
  Future<void> crateApiSimpleRagClearAllDocuments({required String dbPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleRagClearAllDocumentsConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRagClearAllDocumentsConstMeta =>
      const TaskConstMeta(
        debugName: "clear_all_documents",
        argNames: ["dbPath"],
      );

  @override
  Future<void> crateApiHnswIndexClearHnswIndex() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHnswIndexClearHnswIndexConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHnswIndexClearHnswIndexConstMeta =>
      const TaskConstMeta(debugName: "clear_hnsw_index", argNames: []);

  @override
  String crateApiTokenizerDecodeTokens({required List<int> tokenIds}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_32_loose(tokenIds, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTokenizerDecodeTokensConstMeta,
        argValues: [tokenIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTokenizerDecodeTokensConstMeta =>
      const TaskConstMeta(debugName: "decode_tokens", argNames: ["tokenIds"]);

  @override
  Future<void> crateApiSourceRagDeleteSource({
    required String dbPath,
    required PlatformInt64 sourceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_i_64(sourceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSourceRagDeleteSourceConstMeta,
        argValues: [dbPath, sourceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSourceRagDeleteSourceConstMeta =>
      const TaskConstMeta(
        debugName: "delete_source",
        argNames: ["dbPath", "sourceId"],
      );

  @override
  Future<EmbeddingPoint> crateApiHnswIndexEmbeddingPointNew({
    required PlatformInt64 id,
    required List<double> embedding,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          sse_encode_list_prim_f_32_loose(embedding, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_embedding_point,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHnswIndexEmbeddingPointNewConstMeta,
        argValues: [id, embedding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHnswIndexEmbeddingPointNewConstMeta =>
      const TaskConstMeta(
        debugName: "embedding_point_new",
        argNames: ["id", "embedding"],
      );

  @override
  Future<PlatformInt64> crateApiSimpleRagGetDocumentCount({
    required String dbPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleRagGetDocumentCountConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRagGetDocumentCountConstMeta =>
      const TaskConstMeta(
        debugName: "get_document_count",
        argNames: ["dbPath"],
      );

  @override
  Future<String?> crateApiSourceRagGetSource({
    required String dbPath,
    required PlatformInt64 sourceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_i_64(sourceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSourceRagGetSourceConstMeta,
        argValues: [dbPath, sourceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSourceRagGetSourceConstMeta => const TaskConstMeta(
    debugName: "get_source",
    argNames: ["dbPath", "sourceId"],
  );

  @override
  Future<List<String>> crateApiSourceRagGetSourceChunks({
    required String dbPath,
    required PlatformInt64 sourceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_i_64(sourceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSourceRagGetSourceChunksConstMeta,
        argValues: [dbPath, sourceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSourceRagGetSourceChunksConstMeta =>
      const TaskConstMeta(
        debugName: "get_source_chunks",
        argNames: ["dbPath", "sourceId"],
      );

  @override
  Future<SourceStats> crateApiSourceRagGetSourceStats({
    required String dbPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_source_stats,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSourceRagGetSourceStatsConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSourceRagGetSourceStatsConstMeta =>
      const TaskConstMeta(debugName: "get_source_stats", argNames: ["dbPath"]);

  @override
  int crateApiTokenizerGetVocabSize() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTokenizerGetVocabSizeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTokenizerGetVocabSizeConstMeta =>
      const TaskConstMeta(debugName: "get_vocab_size", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiSimpleRagInitDb({required String dbPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleRagInitDbConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRagInitDbConstMeta =>
      const TaskConstMeta(debugName: "init_db", argNames: ["dbPath"]);

  @override
  Future<void> crateApiSourceRagInitSourceDb({required String dbPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSourceRagInitSourceDbConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSourceRagInitSourceDbConstMeta =>
      const TaskConstMeta(debugName: "init_source_db", argNames: ["dbPath"]);

  @override
  Future<void> crateApiTokenizerInitTokenizer({required String tokenizerPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(tokenizerPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTokenizerInitTokenizerConstMeta,
        argValues: [tokenizerPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTokenizerInitTokenizerConstMeta =>
      const TaskConstMeta(
        debugName: "init_tokenizer",
        argNames: ["tokenizerPath"],
      );

  @override
  Future<bool> crateApiHnswIndexIsHnswIndexLoaded() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHnswIndexIsHnswIndexLoadedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHnswIndexIsHnswIndexLoadedConstMeta =>
      const TaskConstMeta(debugName: "is_hnsw_index_loaded", argNames: []);

  @override
  Future<void> crateApiSourceRagRebuildChunkHnswIndex({
    required String dbPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSourceRagRebuildChunkHnswIndexConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSourceRagRebuildChunkHnswIndexConstMeta =>
      const TaskConstMeta(
        debugName: "rebuild_chunk_hnsw_index",
        argNames: ["dbPath"],
      );

  @override
  Future<void> crateApiSimpleRagRebuildHnswIndex({required String dbPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleRagRebuildHnswIndexConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRagRebuildHnswIndexConstMeta =>
      const TaskConstMeta(
        debugName: "rebuild_hnsw_index",
        argNames: ["dbPath"],
      );

  @override
  Future<List<ChunkSearchResult>> crateApiSourceRagSearchChunks({
    required String dbPath,
    required List<double> queryEmbedding,
    required int topK,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_list_prim_f_32_loose(queryEmbedding, serializer);
          sse_encode_u_32(topK, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chunk_search_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSourceRagSearchChunksConstMeta,
        argValues: [dbPath, queryEmbedding, topK],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSourceRagSearchChunksConstMeta =>
      const TaskConstMeta(
        debugName: "search_chunks",
        argNames: ["dbPath", "queryEmbedding", "topK"],
      );

  @override
  Future<List<HnswSearchResult>> crateApiHnswIndexSearchHnsw({
    required List<double> queryEmbedding,
    required BigInt topK,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_32_loose(queryEmbedding, serializer);
          sse_encode_usize(topK, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_hnsw_search_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHnswIndexSearchHnswConstMeta,
        argValues: [queryEmbedding, topK],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHnswIndexSearchHnswConstMeta =>
      const TaskConstMeta(
        debugName: "search_hnsw",
        argNames: ["queryEmbedding", "topK"],
      );

  @override
  Future<List<String>> crateApiSimpleRagSearchSimilar({
    required String dbPath,
    required List<double> queryEmbedding,
    required int topK,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_list_prim_f_32_loose(queryEmbedding, serializer);
          sse_encode_u_32(topK, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleRagSearchSimilarConstMeta,
        argValues: [dbPath, queryEmbedding, topK],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRagSearchSimilarConstMeta =>
      const TaskConstMeta(
        debugName: "search_similar",
        argNames: ["dbPath", "queryEmbedding", "topK"],
      );

  @override
  List<SemanticChunk> crateApiSemanticChunkerSemanticChunk({
    required String text,
    required int maxChars,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_i_32(maxChars, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_semantic_chunk,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSemanticChunkerSemanticChunkConstMeta,
        argValues: [text, maxChars],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSemanticChunkerSemanticChunkConstMeta =>
      const TaskConstMeta(
        debugName: "semantic_chunk",
        argNames: ["text", "maxChars"],
      );

  @override
  List<SemanticChunk> crateApiSemanticChunkerSemanticChunkWithOverlap({
    required String text,
    required int maxChars,
    required int overlapChars,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_i_32(maxChars, serializer);
          sse_encode_i_32(overlapChars, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_semantic_chunk,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSemanticChunkerSemanticChunkWithOverlapConstMeta,
        argValues: [text, maxChars, overlapChars],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSemanticChunkerSemanticChunkWithOverlapConstMeta =>
      const TaskConstMeta(
        debugName: "semantic_chunk_with_overlap",
        argNames: ["text", "maxChars", "overlapChars"],
      );

  @override
  Uint32List crateApiTokenizerTokenize({required String text}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_32_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTokenizerTokenizeConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTokenizerTokenizeConstMeta =>
      const TaskConstMeta(debugName: "tokenize", argNames: ["text"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AddDocumentResult dco_decode_add_document_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AddDocumentResult(
      success: dco_decode_bool(arr[0]),
      isDuplicate: dco_decode_bool(arr[1]),
      message: dco_decode_String(arr[2]),
    );
  }

  @protected
  AddSourceResult dco_decode_add_source_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AddSourceResult(
      sourceId: dco_decode_i_64(arr[0]),
      isDuplicate: dco_decode_bool(arr[1]),
      chunkCount: dco_decode_i_32(arr[2]),
      message: dco_decode_String(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ChunkData dco_decode_chunk_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ChunkData(
      content: dco_decode_String(arr[0]),
      chunkIndex: dco_decode_i_32(arr[1]),
      startPos: dco_decode_i_32(arr[2]),
      endPos: dco_decode_i_32(arr[3]),
      embedding: dco_decode_list_prim_f_32_strict(arr[4]),
    );
  }

  @protected
  ChunkSearchResult dco_decode_chunk_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ChunkSearchResult(
      chunkId: dco_decode_i_64(arr[0]),
      sourceId: dco_decode_i_64(arr[1]),
      chunkIndex: dco_decode_i_32(arr[2]),
      content: dco_decode_String(arr[3]),
      similarity: dco_decode_f_64(arr[4]),
    );
  }

  @protected
  EmbeddingPoint dco_decode_embedding_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return EmbeddingPoint(
      id: dco_decode_i_64(arr[0]),
      embedding: dco_decode_list_prim_f_32_strict(arr[1]),
      norm: dco_decode_f_32(arr[2]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  HnswSearchResult dco_decode_hnsw_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return HnswSearchResult(
      id: dco_decode_i_64(arr[0]),
      distance: dco_decode_f_32(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ChunkData> dco_decode_list_chunk_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chunk_data).toList();
  }

  @protected
  List<ChunkSearchResult> dco_decode_list_chunk_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chunk_search_result).toList();
  }

  @protected
  List<HnswSearchResult> dco_decode_list_hnsw_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_hnsw_search_result).toList();
  }

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(PlatformInt64, Float32List)>
  dco_decode_list_record_i_64_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_i_64_list_prim_f_32_strict)
        .toList();
  }

  @protected
  List<SemanticChunk> dco_decode_list_semantic_chunk(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_semantic_chunk).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  (PlatformInt64, Float32List) dco_decode_record_i_64_list_prim_f_32_strict(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_i_64(arr[0]), dco_decode_list_prim_f_32_strict(arr[1]));
  }

  @protected
  SemanticChunk dco_decode_semantic_chunk(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SemanticChunk(
      index: dco_decode_i_32(arr[0]),
      content: dco_decode_String(arr[1]),
      startPos: dco_decode_i_32(arr[2]),
      endPos: dco_decode_i_32(arr[3]),
    );
  }

  @protected
  SourceStats dco_decode_source_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SourceStats(
      sourceCount: dco_decode_i_64(arr[0]),
      chunkCount: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AddDocumentResult sse_decode_add_document_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_isDuplicate = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    return AddDocumentResult(
      success: var_success,
      isDuplicate: var_isDuplicate,
      message: var_message,
    );
  }

  @protected
  AddSourceResult sse_decode_add_source_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourceId = sse_decode_i_64(deserializer);
    var var_isDuplicate = sse_decode_bool(deserializer);
    var var_chunkCount = sse_decode_i_32(deserializer);
    var var_message = sse_decode_String(deserializer);
    return AddSourceResult(
      sourceId: var_sourceId,
      isDuplicate: var_isDuplicate,
      chunkCount: var_chunkCount,
      message: var_message,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ChunkData sse_decode_chunk_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_content = sse_decode_String(deserializer);
    var var_chunkIndex = sse_decode_i_32(deserializer);
    var var_startPos = sse_decode_i_32(deserializer);
    var var_endPos = sse_decode_i_32(deserializer);
    var var_embedding = sse_decode_list_prim_f_32_strict(deserializer);
    return ChunkData(
      content: var_content,
      chunkIndex: var_chunkIndex,
      startPos: var_startPos,
      endPos: var_endPos,
      embedding: var_embedding,
    );
  }

  @protected
  ChunkSearchResult sse_decode_chunk_search_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chunkId = sse_decode_i_64(deserializer);
    var var_sourceId = sse_decode_i_64(deserializer);
    var var_chunkIndex = sse_decode_i_32(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_similarity = sse_decode_f_64(deserializer);
    return ChunkSearchResult(
      chunkId: var_chunkId,
      sourceId: var_sourceId,
      chunkIndex: var_chunkIndex,
      content: var_content,
      similarity: var_similarity,
    );
  }

  @protected
  EmbeddingPoint sse_decode_embedding_point(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_embedding = sse_decode_list_prim_f_32_strict(deserializer);
    var var_norm = sse_decode_f_32(deserializer);
    return EmbeddingPoint(id: var_id, embedding: var_embedding, norm: var_norm);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  HnswSearchResult sse_decode_hnsw_search_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_distance = sse_decode_f_32(deserializer);
    return HnswSearchResult(id: var_id, distance: var_distance);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChunkData> sse_decode_list_chunk_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChunkData>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chunk_data(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChunkSearchResult> sse_decode_list_chunk_search_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChunkSearchResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chunk_search_result(deserializer));
    }
    return ans_;
  }

  @protected
  List<HnswSearchResult> sse_decode_list_hnsw_search_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HnswSearchResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_hnsw_search_result(deserializer));
    }
    return ans_;
  }

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(PlatformInt64, Float32List)>
  sse_decode_list_record_i_64_list_prim_f_32_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(PlatformInt64, Float32List)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_i_64_list_prim_f_32_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<SemanticChunk> sse_decode_list_semantic_chunk(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SemanticChunk>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_semantic_chunk(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (PlatformInt64, Float32List) sse_decode_record_i_64_list_prim_f_32_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_i_64(deserializer);
    var var_field1 = sse_decode_list_prim_f_32_strict(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  SemanticChunk sse_decode_semantic_chunk(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_i_32(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_startPos = sse_decode_i_32(deserializer);
    var var_endPos = sse_decode_i_32(deserializer);
    return SemanticChunk(
      index: var_index,
      content: var_content,
      startPos: var_startPos,
      endPos: var_endPos,
    );
  }

  @protected
  SourceStats sse_decode_source_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourceCount = sse_decode_i_64(deserializer);
    var var_chunkCount = sse_decode_i_64(deserializer);
    return SourceStats(
      sourceCount: var_sourceCount,
      chunkCount: var_chunkCount,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_add_document_result(
    AddDocumentResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_bool(self.isDuplicate, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_add_source_result(
    AddSourceResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.sourceId, serializer);
    sse_encode_bool(self.isDuplicate, serializer);
    sse_encode_i_32(self.chunkCount, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_chunk_data(ChunkData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.content, serializer);
    sse_encode_i_32(self.chunkIndex, serializer);
    sse_encode_i_32(self.startPos, serializer);
    sse_encode_i_32(self.endPos, serializer);
    sse_encode_list_prim_f_32_strict(self.embedding, serializer);
  }

  @protected
  void sse_encode_chunk_search_result(
    ChunkSearchResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.chunkId, serializer);
    sse_encode_i_64(self.sourceId, serializer);
    sse_encode_i_32(self.chunkIndex, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_f_64(self.similarity, serializer);
  }

  @protected
  void sse_encode_embedding_point(
    EmbeddingPoint self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_list_prim_f_32_strict(self.embedding, serializer);
    sse_encode_f_32(self.norm, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_hnsw_search_result(
    HnswSearchResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_f_32(self.distance, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chunk_data(
    List<ChunkData> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chunk_data(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chunk_search_result(
    List<ChunkSearchResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chunk_search_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_hnsw_search_result(
    List<HnswSearchResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_hnsw_search_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(
      self is Float32List ? self : Float32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_32_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(
      self is Uint32List ? self : Uint32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_i_64_list_prim_f_32_strict(
    List<(PlatformInt64, Float32List)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_i_64_list_prim_f_32_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_semantic_chunk(
    List<SemanticChunk> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_semantic_chunk(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_record_i_64_list_prim_f_32_strict(
    (PlatformInt64, Float32List) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.$1, serializer);
    sse_encode_list_prim_f_32_strict(self.$2, serializer);
  }

  @protected
  void sse_encode_semantic_chunk(SemanticChunk self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_i_32(self.startPos, serializer);
    sse_encode_i_32(self.endPos, serializer);
  }

  @protected
  void sse_encode_source_stats(SourceStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.sourceCount, serializer);
    sse_encode_i_64(self.chunkCount, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
