// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/bm25_search.dart';
import 'api/compression_utils.dart';
import 'api/db_pool.dart';
import 'api/document_parser.dart';
import 'api/error.dart';
import 'api/hnsw_index.dart';
import 'api/hybrid_search.dart';
import 'api/incremental_index.dart';
import 'api/logger.dart';
import 'api/semantic_chunker.dart';
import 'api/simple.dart';
import 'api/simple_rag.dart';
import 'api/source_rag.dart';
import 'api/tokenizer.dart';
import 'api/user_intent.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AddDocumentResult dco_decode_add_document_result(dynamic raw);

  @protected
  AddSourceResult dco_decode_add_source_result(dynamic raw);

  @protected
  Bm25SearchResult dco_decode_bm_25_search_result(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CompressionOptions dco_decode_box_autoadd_compression_options(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  (int, int, int) dco_decode_box_autoadd_record_u_32_u_32_u_32(dynamic raw);

  @protected
  RrfConfig dco_decode_box_autoadd_rrf_config(dynamic raw);

  @protected
  SearchFilter dco_decode_box_autoadd_search_filter(dynamic raw);

  @protected
  UserIntent dco_decode_box_autoadd_user_intent(dynamic raw);

  @protected
  BufferStats dco_decode_buffer_stats(dynamic raw);

  @protected
  ChunkData dco_decode_chunk_data(dynamic raw);

  @protected
  ChunkForReembedding dco_decode_chunk_for_reembedding(dynamic raw);

  @protected
  ChunkSearchResult dco_decode_chunk_search_result(dynamic raw);

  @protected
  ChunkType dco_decode_chunk_type(dynamic raw);

  @protected
  CompressedText dco_decode_compressed_text(dynamic raw);

  @protected
  CompressionOptions dco_decode_compression_options(dynamic raw);

  @protected
  EmbeddingPoint dco_decode_embedding_point(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  HnswSearchResult dco_decode_hnsw_search_result(dynamic raw);

  @protected
  HybridSearchResult dco_decode_hybrid_search_result(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IncrementalSearchResult dco_decode_incremental_search_result(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Bm25SearchResult> dco_decode_list_bm_25_search_result(dynamic raw);

  @protected
  List<ChunkData> dco_decode_list_chunk_data(dynamic raw);

  @protected
  List<ChunkForReembedding> dco_decode_list_chunk_for_reembedding(dynamic raw);

  @protected
  List<ChunkSearchResult> dco_decode_list_chunk_search_result(dynamic raw);

  @protected
  List<HnswSearchResult> dco_decode_list_hnsw_search_result(dynamic raw);

  @protected
  List<HybridSearchResult> dco_decode_list_hybrid_search_result(dynamic raw);

  @protected
  List<IncrementalSearchResult> dco_decode_list_incremental_search_result(
    dynamic raw,
  );

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(PlatformInt64, Float32List)>
  dco_decode_list_record_i_64_list_prim_f_32_strict(dynamic raw);

  @protected
  List<(PlatformInt64, String)> dco_decode_list_record_i_64_string(dynamic raw);

  @protected
  List<SemanticChunk> dco_decode_list_semantic_chunk(dynamic raw);

  @protected
  List<SourceEntry> dco_decode_list_source_entry(dynamic raw);

  @protected
  List<StructuredChunk> dco_decode_list_structured_chunk(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  (int, int, int)? dco_decode_opt_box_autoadd_record_u_32_u_32_u_32(
    dynamic raw,
  );

  @protected
  RrfConfig? dco_decode_opt_box_autoadd_rrf_config(dynamic raw);

  @protected
  SearchFilter? dco_decode_opt_box_autoadd_search_filter(dynamic raw);

  @protected
  Int64List? dco_decode_opt_list_prim_i_64_strict(dynamic raw);

  @protected
  ParsedIntent dco_decode_parsed_intent(dynamic raw);

  @protected
  RagError dco_decode_rag_error(dynamic raw);

  @protected
  (PlatformInt64, Float32List) dco_decode_record_i_64_list_prim_f_32_strict(
    dynamic raw,
  );

  @protected
  (PlatformInt64, String) dco_decode_record_i_64_string(dynamic raw);

  @protected
  (int, int, int) dco_decode_record_u_32_u_32_u_32(dynamic raw);

  @protected
  RrfConfig dco_decode_rrf_config(dynamic raw);

  @protected
  SearchFilter dco_decode_search_filter(dynamic raw);

  @protected
  SemanticChunk dco_decode_semantic_chunk(dynamic raw);

  @protected
  SourceEntry dco_decode_source_entry(dynamic raw);

  @protected
  SourceStats dco_decode_source_stats(dynamic raw);

  @protected
  StructuredChunk dco_decode_structured_chunk(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserIntent dco_decode_user_intent(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AddDocumentResult sse_decode_add_document_result(
    SseDeserializer deserializer,
  );

  @protected
  AddSourceResult sse_decode_add_source_result(SseDeserializer deserializer);

  @protected
  Bm25SearchResult sse_decode_bm_25_search_result(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CompressionOptions sse_decode_box_autoadd_compression_options(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  (int, int, int) sse_decode_box_autoadd_record_u_32_u_32_u_32(
    SseDeserializer deserializer,
  );

  @protected
  RrfConfig sse_decode_box_autoadd_rrf_config(SseDeserializer deserializer);

  @protected
  SearchFilter sse_decode_box_autoadd_search_filter(
    SseDeserializer deserializer,
  );

  @protected
  UserIntent sse_decode_box_autoadd_user_intent(SseDeserializer deserializer);

  @protected
  BufferStats sse_decode_buffer_stats(SseDeserializer deserializer);

  @protected
  ChunkData sse_decode_chunk_data(SseDeserializer deserializer);

  @protected
  ChunkForReembedding sse_decode_chunk_for_reembedding(
    SseDeserializer deserializer,
  );

  @protected
  ChunkSearchResult sse_decode_chunk_search_result(
    SseDeserializer deserializer,
  );

  @protected
  ChunkType sse_decode_chunk_type(SseDeserializer deserializer);

  @protected
  CompressedText sse_decode_compressed_text(SseDeserializer deserializer);

  @protected
  CompressionOptions sse_decode_compression_options(
    SseDeserializer deserializer,
  );

  @protected
  EmbeddingPoint sse_decode_embedding_point(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  HnswSearchResult sse_decode_hnsw_search_result(SseDeserializer deserializer);

  @protected
  HybridSearchResult sse_decode_hybrid_search_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IncrementalSearchResult sse_decode_incremental_search_result(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Bm25SearchResult> sse_decode_list_bm_25_search_result(
    SseDeserializer deserializer,
  );

  @protected
  List<ChunkData> sse_decode_list_chunk_data(SseDeserializer deserializer);

  @protected
  List<ChunkForReembedding> sse_decode_list_chunk_for_reembedding(
    SseDeserializer deserializer,
  );

  @protected
  List<ChunkSearchResult> sse_decode_list_chunk_search_result(
    SseDeserializer deserializer,
  );

  @protected
  List<HnswSearchResult> sse_decode_list_hnsw_search_result(
    SseDeserializer deserializer,
  );

  @protected
  List<HybridSearchResult> sse_decode_list_hybrid_search_result(
    SseDeserializer deserializer,
  );

  @protected
  List<IncrementalSearchResult> sse_decode_list_incremental_search_result(
    SseDeserializer deserializer,
  );

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(PlatformInt64, Float32List)>
  sse_decode_list_record_i_64_list_prim_f_32_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<(PlatformInt64, String)> sse_decode_list_record_i_64_string(
    SseDeserializer deserializer,
  );

  @protected
  List<SemanticChunk> sse_decode_list_semantic_chunk(
    SseDeserializer deserializer,
  );

  @protected
  List<SourceEntry> sse_decode_list_source_entry(SseDeserializer deserializer);

  @protected
  List<StructuredChunk> sse_decode_list_structured_chunk(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  (int, int, int)? sse_decode_opt_box_autoadd_record_u_32_u_32_u_32(
    SseDeserializer deserializer,
  );

  @protected
  RrfConfig? sse_decode_opt_box_autoadd_rrf_config(
    SseDeserializer deserializer,
  );

  @protected
  SearchFilter? sse_decode_opt_box_autoadd_search_filter(
    SseDeserializer deserializer,
  );

  @protected
  Int64List? sse_decode_opt_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  ParsedIntent sse_decode_parsed_intent(SseDeserializer deserializer);

  @protected
  RagError sse_decode_rag_error(SseDeserializer deserializer);

  @protected
  (PlatformInt64, Float32List) sse_decode_record_i_64_list_prim_f_32_strict(
    SseDeserializer deserializer,
  );

  @protected
  (PlatformInt64, String) sse_decode_record_i_64_string(
    SseDeserializer deserializer,
  );

  @protected
  (int, int, int) sse_decode_record_u_32_u_32_u_32(
    SseDeserializer deserializer,
  );

  @protected
  RrfConfig sse_decode_rrf_config(SseDeserializer deserializer);

  @protected
  SearchFilter sse_decode_search_filter(SseDeserializer deserializer);

  @protected
  SemanticChunk sse_decode_semantic_chunk(SseDeserializer deserializer);

  @protected
  SourceEntry sse_decode_source_entry(SseDeserializer deserializer);

  @protected
  SourceStats sse_decode_source_stats(SseDeserializer deserializer);

  @protected
  StructuredChunk sse_decode_structured_chunk(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserIntent sse_decode_user_intent(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_add_document_result(
    AddDocumentResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_add_source_result(
    AddSourceResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bm_25_search_result(
    Bm25SearchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_compression_options(
    CompressionOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_record_u_32_u_32_u_32(
    (int, int, int) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rrf_config(
    RrfConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_search_filter(
    SearchFilter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_user_intent(
    UserIntent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_buffer_stats(BufferStats self, SseSerializer serializer);

  @protected
  void sse_encode_chunk_data(ChunkData self, SseSerializer serializer);

  @protected
  void sse_encode_chunk_for_reembedding(
    ChunkForReembedding self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chunk_search_result(
    ChunkSearchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chunk_type(ChunkType self, SseSerializer serializer);

  @protected
  void sse_encode_compressed_text(
    CompressedText self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_compression_options(
    CompressionOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_embedding_point(
    EmbeddingPoint self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_hnsw_search_result(
    HnswSearchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_hybrid_search_result(
    HybridSearchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_incremental_search_result(
    IncrementalSearchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bm_25_search_result(
    List<Bm25SearchResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_chunk_data(
    List<ChunkData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_chunk_for_reembedding(
    List<ChunkForReembedding> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_chunk_search_result(
    List<ChunkSearchResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_hnsw_search_result(
    List<HnswSearchResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_hybrid_search_result(
    List<HybridSearchResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_incremental_search_result(
    List<IncrementalSearchResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_i_64_list_prim_f_32_strict(
    List<(PlatformInt64, Float32List)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_i_64_string(
    List<(PlatformInt64, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_semantic_chunk(
    List<SemanticChunk> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_source_entry(
    List<SourceEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_structured_chunk(
    List<StructuredChunk> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_record_u_32_u_32_u_32(
    (int, int, int)? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_rrf_config(
    RrfConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_search_filter(
    SearchFilter? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_i_64_strict(
    Int64List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_parsed_intent(ParsedIntent self, SseSerializer serializer);

  @protected
  void sse_encode_rag_error(RagError self, SseSerializer serializer);

  @protected
  void sse_encode_record_i_64_list_prim_f_32_strict(
    (PlatformInt64, Float32List) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_i_64_string(
    (PlatformInt64, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_32_u_32_u_32(
    (int, int, int) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rrf_config(RrfConfig self, SseSerializer serializer);

  @protected
  void sse_encode_search_filter(SearchFilter self, SseSerializer serializer);

  @protected
  void sse_encode_semantic_chunk(SemanticChunk self, SseSerializer serializer);

  @protected
  void sse_encode_source_entry(SourceEntry self, SseSerializer serializer);

  @protected
  void sse_encode_source_stats(SourceStats self, SseSerializer serializer);

  @protected
  void sse_encode_structured_chunk(
    StructuredChunk self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_intent(UserIntent self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
