// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `tokenize_for_bm25`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DocMeta`, `InvertedIndex`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `add_document`, `clear`, `is_empty`, `len`, `new`, `remove_document`, `search`

/// Add document to BM25 index
Future<void> bm25AddDocument({
  required PlatformInt64 docId,
  required String content,
}) => RustLib.instance.api.crateApiBm25SearchBm25AddDocument(
  docId: docId,
  content: content,
);

/// Add multiple documents to BM25 index (batch)
Future<void> bm25AddDocuments({required List<(PlatformInt64, String)> docs}) =>
    RustLib.instance.api.crateApiBm25SearchBm25AddDocuments(docs: docs);

/// Remove document from BM25 index
Future<void> bm25RemoveDocument({required PlatformInt64 docId}) =>
    RustLib.instance.api.crateApiBm25SearchBm25RemoveDocument(docId: docId);

/// Search using BM25
Future<List<Bm25SearchResult>> bm25Search({
  required String query,
  required int topK,
}) =>
    RustLib.instance.api.crateApiBm25SearchBm25Search(query: query, topK: topK);

/// Clear BM25 index
Future<void> bm25ClearIndex() =>
    RustLib.instance.api.crateApiBm25SearchBm25ClearIndex();

/// Check if BM25 index is loaded
Future<bool> isBm25IndexLoaded() =>
    RustLib.instance.api.crateApiBm25SearchIsBm25IndexLoaded();

/// Get BM25 index document count
Future<BigInt> bm25GetDocumentCount() =>
    RustLib.instance.api.crateApiBm25SearchBm25GetDocumentCount();

/// BM25 search result
class Bm25SearchResult {
  final PlatformInt64 docId;
  final double score;

  const Bm25SearchResult({required this.docId, required this.score});

  @override
  int get hashCode => docId.hashCode ^ score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Bm25SearchResult &&
          runtimeType == other.runtimeType &&
          docId == other.docId &&
          score == other.score;
}
