// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_connection`

/// Initialize the global connection pool with optimized SQLite settings.
///
/// This should be called once during application startup, before any database operations.
///
/// # Arguments
/// * `db_path` - Path to the SQLite database file
/// * `max_size` - Maximum number of connections in the pool (default: 4)
///
/// # SQLite Optimizations
/// - WAL mode: Better concurrency for read-heavy workloads
/// - 64MB page cache: Reduces disk I/O
/// - Memory temp storage: Faster temporary operations
/// - 256MB mmap: Memory-mapped I/O for large databases
///
/// # Example
/// ```rust
/// init_db_pool("/path/to/rag.sqlite", 4)?;
/// ```
Future<void> initDbPool({required String dbPath, required int maxSize}) =>
    RustLib.instance.api.crateApiDbPoolInitDbPool(
      dbPath: dbPath,
      maxSize: maxSize,
    );

/// Check if the connection pool is initialized.
Future<bool> isPoolInitialized() =>
    RustLib.instance.api.crateApiDbPoolIsPoolInitialized();

/// Get pool statistics for monitoring.
///
/// Returns (active_connections, idle_connections, max_size)
Future<(int, int, int)?> getPoolStats() =>
    RustLib.instance.api.crateApiDbPoolGetPoolStats();

/// Close the connection pool and release all resources.
///
/// This should be called during application shutdown. After calling this,
/// you must call `init_db_pool` again before using database operations.
Future<void> closeDbPool() => RustLib.instance.api.crateApiDbPoolCloseDbPool();
