// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dehyphenate`

/// Extract text content from a PDF file (bytes)
/// Includes dehyphenation to fix line-break word splits
Future<String> extractTextFromPdf({required List<int> fileBytes}) => RustLib
    .instance
    .api
    .crateApiDocumentParserExtractTextFromPdf(fileBytes: fileBytes);

/// Extract text content from a DOCX file (bytes)
Future<String> extractTextFromDocx({required List<int> fileBytes}) => RustLib
    .instance
    .api
    .crateApiDocumentParserExtractTextFromDocx(fileBytes: fileBytes);

/// Auto-detect document type and extract text
/// Uses magic bytes to determine file format
Future<String> extractTextFromDocument({required List<int> fileBytes}) =>
    RustLib.instance.api.crateApiDocumentParserExtractTextFromDocument(
      fileBytes: fileBytes,
    );
