// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`

@freezed
sealed class RagError with _$RagError implements FrbException {
  const RagError._();

  /// Database related error (potential for retry).
  const factory RagError.databaseError(String field0) = RagError_DatabaseError;

  /// I/O error (file missing, permission issues, etc.).
  const factory RagError.ioError(String field0) = RagError_IoError;

  /// Failed to load embedding model.
  const factory RagError.modelLoadError(String field0) =
      RagError_ModelLoadError;

  /// User input error (invalid query, etc.).
  const factory RagError.invalidInput(String field0) = RagError_InvalidInput;

  /// Internal system error (HNSW, Logic, etc.).
  const factory RagError.internalError(String field0) = RagError_InternalError;

  /// Unknown error.
  const factory RagError.unknown(String field0) = RagError_Unknown;
}
