// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CombinedLogger`, `DART_LOG_SINK`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `enabled`, `flush`, `initialize`, `log`

/// Initialize the global logger.
///
/// This function is idempotent - calling it multiple times is safe and will
/// simply return Ok(()) if the logger is already initialized.
///
/// Log levels:
/// - Debug builds: DEBUG and above
/// - Release builds: INFO and above
Future<void> initLogger() => RustLib.instance.api.crateApiLoggerInitLogger();

/// Initialize the Dart log stream.
/// Call this from Dart to start receiving Rust logs.
Stream<String> initLogStream() =>
    RustLib.instance.api.crateApiLoggerInitLogStream();

/// Close the Dart log stream.
/// Call this when disposing the log subscription to prevent memory leaks.
void closeLogStream() => RustLib.instance.api.crateApiLoggerCloseLogStream();

/// Helper to send a log message to Dart if the stream is active.
/// Takes a reference to avoid unnecessary cloning when sink is not available.
Future<void> sendLogToDart({required String msg}) =>
    RustLib.instance.api.crateApiLoggerSendLogToDart(msg: msg);
