// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialize tokenizer with tokenizer.json file path.
Future<void> initTokenizer({required String tokenizerPath}) => RustLib
    .instance
    .api
    .crateApiTokenizerInitTokenizer(tokenizerPath: tokenizerPath);

/// Tokenize text (returns token IDs with CLS/SEP tokens).
Uint32List tokenize({required String text}) =>
    RustLib.instance.api.crateApiTokenizerTokenize(text: text);

/// Decode token IDs to text.
String decodeTokens({required List<int> tokenIds}) =>
    RustLib.instance.api.crateApiTokenizerDecodeTokens(tokenIds: tokenIds);

/// Get vocab size.
int getVocabSize() => RustLib.instance.api.crateApiTokenizerGetVocabSize();
