// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'user_intent.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `fmt`, `fmt`

/// Parse user input into a UserIntent.
UserIntent parseUserIntent({required String input}) =>
    RustLib.instance.api.crateApiUserIntentParseUserIntent(input: input);

/// Parse intent (FRB-friendly wrapper).
ParsedIntent parseIntent({required String input}) =>
    RustLib.instance.api.crateApiUserIntentParseIntent(input: input);

class ParsedIntent {
  final String intentType;
  final String query;
  final bool isValid;
  final String? errorMessage;

  const ParsedIntent({
    required this.intentType,
    required this.query,
    required this.isValid,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      intentType.hashCode ^
      query.hashCode ^
      isValid.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParsedIntent &&
          runtimeType == other.runtimeType &&
          intentType == other.intentType &&
          query == other.query &&
          isValid == other.isValid &&
          errorMessage == other.errorMessage;
}

@freezed
sealed class UserIntent with _$UserIntent {
  const UserIntent._();

  const factory UserIntent.summary({required String query}) =
      UserIntent_Summary;
  const factory UserIntent.define({required String term}) = UserIntent_Define;
  const factory UserIntent.expandKnowledge({required String query}) =
      UserIntent_ExpandKnowledge;
  const factory UserIntent.general({required String query}) =
      UserIntent_General;
  const factory UserIntent.invalidCommand({
    required String command,
    required String reason,
  }) = UserIntent_InvalidCommand;

  Future<void> getQuery() =>
      RustLib.instance.api.crateApiUserIntentUserIntentGetQuery(that: this);

  Future<void> intentType() =>
      RustLib.instance.api.crateApiUserIntentUserIntentIntentType(that: this);
}
